language: python

before_cache:
  - brew cleanup

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/Homebrew
    - $HOME/HomebrewLocal
    - /Library/Caches/Homebrew

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - PY_VERSION=3
        - PY_VERSION_=3.7
        - MAKEFLAGS=-j8

before_install:
  - source buildconfig/ci/travis/testy.sh
